---

- name: Fail if required stirling_pdf settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - stirling_pdf_uid
    - stirling_pdf_gid
    - stirling_pdf_hostname
